/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Desafio Include</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="omega_symbol__god_of_war_2018__by_rootofalllight_dep78an-fullview.ico" />
      </Head>
      <header style={{background:"#010326",height:"70px",position:'fixed',width:'100%', zIndex:"10"}} >
        <div>
        <a href=""><Image src= "/image/god_of_war_ragnarok_logo_freelogovectors.net_.webp" width={148.15} height={40} style={{position:"absolute",marginTop:"15px"}}  /></a>
        <nav className={styles.navg} >
          <a href="#homepers">Home</a>
          <a href="#jogosGod">Jogos</a>
          <a href="#Historia">História</a>
          <a href="#personagensSeq">Personagens</a>
          
        </nav>
        </div>
      </header>
      <main >
        <div id="homepers"><h2 className={styles.fonte} style={{color:"#1D3A53"}}>Personagens</h2></div>
        <span className={styles.fospan} style={{color:"#1D3A53"}}>principais</span>
        <div > 
          <Image src="/image/Imagens de fundo/1267491.jpg" width={1440} height={821} style={{display:"flex"}}/>  
          
          <div className={styles.description}>
            <a href="#historiKratos" style={{marginLeft:"0px"}}>
          <Image className={styles.kratos} src="/image/personagens/Kratos-_GOW_Ragnarok.webp" width={284.750} height={458}/>
          </a>
          <a href="#historiaAtreus" style={{marginLeft:"0px"}}>
          <Image className={styles.atreus} src= "/image/personagens/Atreus_ragnorak.webp" width={274.359} height={415.969}/>
          </a>
          </div>
        </div>

        <div id="Historia">
          <Image src="/image/Imagens de fundo/novo-gow-ps5.jpg" width={1451} height={803} style={{display:"flex"}}/>
        <article style={{position:"absolute",marginTop:"-657px",textAlign:"center",lineHeight:"1.2"}}>
          <h2 className={styles.fonte} style={{color:"#0082B5",marginTop:"-80px",marginLeft:"625px"}} >História</h2>
          <p className={styles.paragr} style={{color:"white"}}>God of War: Ragnarok, se passa três anos após o evento do jogo de 2018, com Atreus um pouco mais velho
            enquanto tenta entender suas origens e a importância de seu nome de batismo — Loki. A busca por respostas vai
            desencadear no auge do Ragnarok, o fim dos tempos Nórdicos.
            Kratos irá auxiliar seu filho em sua jornada por explicações, acompanhado novamente da cabeça de Mimir. Em
            algum momento de sua busca os personagens irão se encontrar com Tyr, o Deus da Guerra Nórdico. Ele foi
            mencionado no jogo anterior, onde todos acreditavam que estava morto, mas que estava somente preso e será
            resgatado por Kratos — para ser um aliado ou inimigo.
            Com o Ragnarok se aproximando a guerra contra Asgard será inevitável e novos inimigos estarão no caminho de
            Atreus. Um deles é Thor, que já apareceu por um breve momento em uma cena pós-créditos do jogo anterior.
            Mas rivais antigos também estão presente. Freya, que jurou destruir Kratos e seu filho após derrotarem
            Baldur, estará de volta. Anteriormente uma aliada, a personagem nutre uma grande ira contra os protagonistas
            e fará de tudo para vingar a morte de seu descendente.</p> 
        </article>
        </div>

        <div id="historiKratos">
          <Image src="/image/Imagens de fundo/textura-de-tela-de-fundo-de-tela-branca-para-fotos-de-pintura-de-fotos-de-alta-qualidade_90380-3178.jpg" width={1511} height={748} style={{display:"flex"}}/>
          <Image src="/image/Imagens de fundo/kratoseatreus.png" width={1385} height={748} style={{position:"absolute",marginTop:"-722px",opacity:"0.9"}}/>
          <article style={{position:"absolute",marginTop:"-657px",textAlign:"center",lineHeight:"1.2"}}>
            <h2 className={styles.fonte} style={{marginTop:"0px",color:"#1D3A53",marginLeft:"625px"}}>Kratos</h2>
            <p className={styles.paragr} style={{marginTop:"75px",color:"#0B0B0B"}}>
            Eu, Kratos, outrora um brutal capitão do exército espartano, liderei meus homens em conquistas por toda a Grécia. No entanto, após ser derrotado por uma horda bárbara brutal, fiz um acordo com o Deus da Guerra, Ares. Sob o nome de Ares, cometi inúmeras atrocidades, buscando espalhar a morte e promovendo a glória de Esparta.

Minha única conexão com a humanidade era minha amada família, mas até eles se horrorizaram comigo. Minha esposa Lysandra afirmou que eu não me importava com a glória de Esparta, apenas comigo mesmo. Ignorando seus avisos, continuei seguindo a vontade de Ares, o que resultou em uma tragédia quando o Deus me enganou para matar minha própria família.

Esse terrível ato me deixou completamente destroçado. Busquei redenção, servindo aos outros deuses do Olimpo, mas a dor de minhas memórias nunca desapareceu. Desenvolvi um profundo ódio pelos deuses, especialmente por Ares, por brincarem com minha vida. Eventualmente, derrotei Ares e me tornei o Deus da Guerra, mas meu ressentimento me levou a entrar em conflito com todos no Olimpo, resultando em uma série de batalhas cataclísmicas que decidiram o destino da Grécia.
            </p>
          </article>
        </div>

        <div id="historiaAtreus">
        <Image src="/image/Imagens de fundo/textura-de-tela-de-fundo-de-tela-branca-para-fotos-de-pintura-de-fotos-de-alta-qualidade_90380-3178.jpg" width={1511} height={748} style={{display:"flex"}} />
        <Image src="/image/Imagens de fundo/atreusfundo.png" width={1385} height={748} style={{position:"absolute",marginTop:"-748px",opacity:"0.9"}}/>
        <article style={{position:"absolute",marginTop:"-657px",textAlign:"center",lineHeight:"1.2"}}>
          <h2 className={styles.fonte} style={{marginTop:"0px",color:"#1D3A53",marginLeft:"625px"}}>Atreus</h2>
          <p className={styles.paragr} style={{marginTop:"200px",color:"#0B0B0B"}}>
          Atreus é um semideus adolescente, filho de Kratos e da Giganta Laufey. Os Gigantes e os Aesir o conhecem como Loki. Com a iminência do Ragnarök, Atreus quer a todo custo explorar e compreender melhor a própria identidade para encontrar seu lugar no mundo. Ele treinou muito com o pai e, embora o relacionamento entre os dois permaneça firme, Atreus anseia por começar a seguir o seu próprio caminho.
          </p>
        </article>
        </div>

        <div id="jogosGod" >
          <Image src="/image/Imagens de fundo/god-of-war-ragnarok-stone-texture-background-3840x1715.webp" width={1444} height={644} style={{display:"flex"}}/>
          <div className={styles.espacogame}>
            <h2 className={styles.fonte} style={{marginTop:"-185px",color:"white",marginLeft:"625px"}}>Jogos</h2>
          <ul style={{display:"flex",alignItems:"flex-end"}}>
            <li>
            <Image src="/image/jogos god of war/God_of_War_2005_capa.png" width={190} height={251.437}/>
            </li>
            <li>
            <Image src="/image/jogos god of war/God_of_War_2_capa.png" width={173} height={246.987}/>
            </li>
            <li>
            <Image src="/image/jogos god of war/God_of_War_3_capa.png" width={216} height={241.011}/>
            </li>
            <li>
            <Image src="/image/jogos god of war/God_of_War_2018_capa.png" width={237} height={251.585}/>
            </li>
            <li>
            <Image src="/image/jogos god of war/God_of_War_Ragnarök_capa.jpg" width={192} height={249.962}/>
            </li>
          </ul>
          </div>
        </div>
        <div id="personagensSeq">
          <h2 className={styles.fonte} style={{color:"#1D3A53"}}>Personagens</h2>
          <span className={styles.fospan} style={{color:"#1D3A53"}}>secundários</span>
          <div>
          <Image src="/image/personagens/section5a-characters-tyr.webp"  width={250} height={620.51} style={{marginTop:"225px",marginLeft:"245px"}}/>
          </div>
          <article className={styles.persoart}>
          <h3>Týr</h3>
          <span>Týr é o deus da guerra Aesir que desapareceu há muito tempo. Ele viajou pelo mundo e se tornou um grande aliado dos Gigantes,</span> <span>buscando a paz entre os Aesir e os Jötnar. Quando Odin violou a paz e declarou guerra a Jötunheim, Týr foi aprisionado.</span>
          </article>
          <div style={{marginTop:"35px"}}>
          <Image src="/image/personagens/section5a-characters-thor.webp"  width={483} height={693.37} style={{marginLeft:"170px"}}/>
          </div>
          <article className={styles.persoart} style={{marginTop:"-578px"}}>
          <h3>Thor</h3>
          <span>Thor, o lendário deus do trovão, é filho de Odin e campeão dos Aesir. Magni e Modi, seus filhos, eram aliados de Baldur e foram mortos por Kratos e Atreus.</span>
          </article>
          <div style={{marginTop:"35px"}}>
          <Image src="/image/personagens/section5a-characters-angrboda.webp"  width={327} height={554.48} style={{marginLeft:"170px"}}/>
          </div>
          <article className={styles.persoart} style={{marginTop:"-455px"}}>
          <h3>Angrboda</h3>
          <span>Angrboda faz parte dos últimos Gigantes que restaram. Após a queda de Jötunheim, ela se escondeu por muitos anos à espera do momento para concretizar as profecias dos Jötnar.</span>
          </article>
          <div style={{marginTop:"35px"}}>
          <Image src="/image/personagens/section5a-characters-freya.webp"  width={359} height={705.49} style={{marginLeft:"170px"}}/>
          </div>
          <article className={styles.persoart} style={{marginTop:"-630px"}}>
          <h3>Freya</h3>
          <span>Freya é uma deusa Vanir, já foi líder das Valquírias, ex-mulher de Odin e antiga rainha dos Aesir. Após a morte do seu amado filho Baldur, que estava afastado dela, Freya jurou uma vingança violenta contra Kratos e Atreus.</span>
          </article>
          <div style={{marginTop:"35px",height:"500px"}}>
          <Image src="/image/personagens/section5a-characters-mimir.webp"  width={144} height={344.18} style={{marginLeft:"170px"}}/>
          </div>
          <article className={styles.persoart} style={{marginTop:"-450px"}}>
          <h3>Mimir</h3>
          <span>Ele pode até ser uma cabeça decepada que depois foi ressuscitada, mas o Mimir continua com o título de homem mais inteligente vivo. Quando Kratos e Atreus o libertaram da árvore em que Odin o mantinha aprisionado, Mimir se juntou à aventura deles e se tornou um amigo de confiança e conselheiro tanto para o pai quanto para o filho. Com os Nove Reinos afundando no caos, agora eles precisarão da sabedoria do Mimir mais do que nunca.</span>
          </article>
        </div>
      </main>
      <footer style={{background:"#010326"}}>
      </footer>
    </>
  )
}
